site_name: OpenBudgeteer Documentation
nav:
    - Home: index.md
    - Quick Start: quick-start.md  
    - Install: install.md
    - Configuration: config.md
    - How to use: how-to.md  
theme:
  name: material
  logo: assets/icon.png
  features:
    - toc.integrate
    - content.code.copy
  palette:
      scheme: slate
      primary: blue grey
      accent: teal

plugins:
  - search
  - glightbox:
      zoomable: true
      draggable: true
      skip_classes:
        - skip-lightbox

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
