site_name: OpenBudgeteer Wiki
site_url: https://openbudgeteer.github.io/Test/
nav:
    - Home: index.md
theme:
  name: material
  logo: assets/icon.png
  features:
    - toc.integrate
    - content.code.copy
  palette:
      scheme: slate
      primary: blue grey
      accent: teal

plugins:
  - search
  - glightbox:
      zoomable: true
      draggable: true
      skip_classes:
        - skip-lightbox

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
