# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish new doc version

on:
  push:
    tags:
      - "*"

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          pip install mkdocs-material mkdocs-glightbox mike
          mike deploy --push -u ${{ github.ref_name }} latest
